name: openmmlab
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - aom=3.9.1=hac33072_0
  - blas=1.0=mkl
  - bzip2=1.0.8=hda65f42_8
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - cairo=1.18.0=hbb29018_2
  - cudatoolkit=11.1.1=hb139c0e_13
  - dav1d=1.2.1=hd590300_0
  - ffmpeg=7.1.0=gpl_he2fd91e_701
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h7e30c49_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=hc364b38_1
  - freetype=2.14.1=ha770c72_0
  - fribidi=1.0.16=hb03c661_0
  - giflib=5.2.2=hd590300_0
  - gmp=6.3.0=hac33072_2
  - graphite2=1.3.14=hecca717_2
  - harfbuzz=9.0.0=hfac3d4d_0
  - icu=73.2=h59595ed_0
  - intel-openmp=2023.0.0=h9e868ea_25371
  - jpeg=9b=h024ee3a_2
  - lame=3.100=h166bdaf_1003
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.44=h153f514_2
  - libabseil=20240722.0=cxx17_hbbce691_4
  - libass=0.17.3=h1dc1e6a_0
  - libblas=3.9.0=1_h86c2bf4_netlib
  - libcblas=3.9.0=13_h8e06fc2_netlib
  - libdrm=2.4.125=hb03c661_1
  - libegl=1.7.0=ha4b6fd6_2
  - libexpat=2.7.3=hecca717_0
  - libffi=3.4.4=h6a678d5_1
  - libfreetype=2.14.1=ha770c72_0
  - libfreetype6=2.14.1=h73754d4_0
  - libgcc=15.2.0=h69a1729_7
  - libgcc-ng=15.2.0=h166f726_7
  - libgfortran=15.2.0=h69a702a_14
  - libgfortran-ng=15.2.0=h69a702a_14
  - libgfortran5=15.2.0=h68bc16d_14
  - libgl=1.7.0=ha4b6fd6_2
  - libglib=2.84.0=h2ff4ddf_0
  - libglvnd=1.7.0=ha4b6fd6_2
  - libglx=1.7.0=ha4b6fd6_2
  - libgomp=15.2.0=h4751f2c_7
  - libhwloc=2.12.1=default_h3d81e11_1000
  - libiconv=1.18=h3b78370_2
  - liblapack=3.9.0=13_h8876d29_netlib
  - libopenvino=2024.4.0=hac27bb2_2
  - libopenvino-auto-batch-plugin=2024.4.0=h4d9b6c2_2
  - libopenvino-auto-plugin=2024.4.0=h4d9b6c2_2
  - libopenvino-hetero-plugin=2024.4.0=h3f63f65_2
  - libopenvino-intel-cpu-plugin=2024.4.0=hac27bb2_2
  - libopenvino-intel-gpu-plugin=2024.4.0=hac27bb2_2
  - libopenvino-intel-npu-plugin=2024.4.0=hac27bb2_2
  - libopenvino-ir-frontend=2024.4.0=h3f63f65_2
  - libopenvino-onnx-frontend=2024.4.0=h5c8f2c3_2
  - libopenvino-paddle-frontend=2024.4.0=h5c8f2c3_2
  - libopenvino-pytorch-frontend=2024.4.0=h5888daf_2
  - libopenvino-tensorflow-frontend=2024.4.0=h6481b9d_2
  - libopenvino-tensorflow-lite-frontend=2024.4.0=h5888daf_2
  - libopus=1.5.2=hd0c01bc_0
  - libpciaccess=0.18=hb9d3cd8_0
  - libpng=1.6.51=h421ea60_0
  - libprotobuf=5.28.2=h5b01275_0
  - libstdcxx=15.2.0=h39759b7_7
  - libstdcxx-ng=15.2.0=hc03a8fd_7
  - libtiff=4.2.0=h85742a9_0
  - libuuid=2.41.2=he9a06e4_0
  - libuv=1.51.0=hb03c661_1
  - libva=2.22.0=h4f16b4b_2
  - libvpx=1.14.1=hac33072_0
  - libwebp=1.2.0=h89dd481_0
  - libwebp-base=1.2.0=h7f98852_2
  - libxcb=1.17.0=h9b100fa_0
  - libxml2=2.13.9=h2c43086_0
  - libzlib=1.3.1=hb25bd0a_0
  - lz4-c=1.9.4=hcb278e6_0
  - mkl=2023.1.0=h213fc3f_46344
  - ncurses=6.5=h7934f7d_0
  - ninja=1.13.2=h171cf75_0
  - numpy=1.24.4=py38h59b608b_0
  - ocl-icd=2.3.3=hb9d3cd8_0
  - opencl-headers=2025.06.13=h5888daf_0
  - openh264=2.4.1=h59595ed_0
  - openssl=3.6.0=h26f9b46_0
  - pcre2=10.44=hc749103_2
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pillow=9.3.0=py38hace64e9_1
  - pip=24.2=py38h06a4308_0
  - pixman=0.46.4=h54a6638_1
  - psutil=5.9.0=py38h5eee18b_0
  - pthread-stubs=0.3=h0ce48e5_1
  - ptyprocess=0.7.0=pyhd3eb1b0_3
  - pugixml=1.14=h59595ed_0
  - python=3.8.20=he870216_0
  - python_abi=3.8=2_cp38
  - pytorch=1.8.0=py3.8_cuda11.1_cudnn8.0.5_0
  - readline=8.3=hc2a1206_0
  - snappy=1.2.2=h03e3b7b_1
  - sqlite=3.51.0=h2a70700_0
  - svt-av1=2.2.1=h5888daf_0
  - tbb=2021.13.0=h8d10470_4
  - tk=8.6.15=h54e0aa7_0
  - torchaudio=0.8.0=py38
  - torchvision=0.9.0=py38_cu111
  - typing_extensions=4.11.0=py38h06a4308_0
  - wayland=1.23.1=h3e06ad9_0
  - wayland-protocols=1.46=hd8ed1ab_0
  - wheel=0.44.0=py38h06a4308_0
  - x264=1!164.3095=h166bdaf_2
  - x265=3.5=h924138e_3
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.6=he73a12e_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-libxext=1.3.6=hb9d3cd8_0
  - xorg-libxfixes=6.0.2=hb03c661_0
  - xorg-libxrender=0.9.12=hb9d3cd8_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.3.1=hb25bd0a_0
  - zstd=1.4.9=haebb681_0
  - pip:
      - addict==2.4.0
      - aliyun-python-sdk-core==2.16.0
      - aliyun-python-sdk-kms==2.16.5
      - catkin-pkg==1.1.0
      - certifi==2025.11.12
      - cffi==1.17.1
      - click==8.1.8
      - colorama==0.4.6
      - crcmod==1.7
      - cryptography==46.0.3
      - cycler==0.12.1
      - distro==1.9.0
      - docutils==0.20.1
      - filelock==3.14.0
      - ftfy==6.2.3
      - idna==3.11
      - jmespath==0.10.0
      - kiwisolver==1.4.7
      - markdown==3.7
      - markdown-it-py==3.0.0
      - mdurl==0.1.2
      - mmcv==2.0.0rc4
      - mmengine==0.10.7
      - model-index==0.1.11
      - opencv-python==4.12.0.88
      - opendatalab==0.0.10
      - openmim==0.3.9
      - openxlab==0.1.3
      - ordered-set==4.1.0
      - oss2==2.17.0
      - prettytable==3.11.0
      - pycparser==2.23
      - pycryptodome==3.23.0
      - pyparsing==3.1.4
      - pytz==2023.4
      - pyyaml==6.0.3
      - regex==2024.11.6
      - requests==2.28.2
      - rich==13.4.2
      - rospkg==1.6.0
      - setuptools==60.2.0
      - six==1.17.0
      - tabulate==0.9.0
      - termcolor==2.4.0
      - tqdm==4.65.2
      - typing-extensions==4.13.2
      - yapf==0.43.0
prefix: /home/mei123/miniconda3/envs/openmmlab
